// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDub-f7OkEeWhYkuYvr-9TEzd-xGMXq-7k',
    appId: '1:498834462860:web:de706da8ad07a0ceb083a9',
    messagingSenderId: '498834462860',
    projectId: 'roamease-509c4',
    authDomain: 'roamease-509c4.firebaseapp.com',
    storageBucket: 'roamease-509c4.firebasestorage.app',
    measurementId: 'G-3QB69BBR0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGezKJLqTpF1dM7SuIMgtlpDOYrhLzx8',
    appId: '1:498834462860:android:5f940e52b105d03db083a9',
    messagingSenderId: '498834462860',
    projectId: 'roamease-509c4',
    storageBucket: 'roamease-509c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrG6hiem9ilBegf5X-yM3qE9CzbC87ubo',
    appId: '1:498834462860:ios:589c153a05c86aaeb083a9',
    messagingSenderId: '498834462860',
    projectId: 'roamease-509c4',
    storageBucket: 'roamease-509c4.firebasestorage.app',
    iosBundleId: 'com.example.psdlProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrG6hiem9ilBegf5X-yM3qE9CzbC87ubo',
    appId: '1:498834462860:ios:589c153a05c86aaeb083a9',
    messagingSenderId: '498834462860',
    projectId: 'roamease-509c4',
    storageBucket: 'roamease-509c4.firebasestorage.app',
    iosBundleId: 'com.example.psdlProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDub-f7OkEeWhYkuYvr-9TEzd-xGMXq-7k',
    appId: '1:498834462860:web:a8e9dd9995b48c60b083a9',
    messagingSenderId: '498834462860',
    projectId: 'roamease-509c4',
    authDomain: 'roamease-509c4.firebaseapp.com',
    storageBucket: 'roamease-509c4.firebasestorage.app',
    measurementId: 'G-176VB2ZRMF',
  );
}
